### PR TITLE
Update FreshPageModelMapper.cs

### PR DESCRIPTION
**Pull request by blackice2999**
Hi,

i think its useful if the FreshPageModelMapper returns "View" instead of "Page" if the ViewModel Name ist "ViewModel" instead of "PageModel".

What do you think about it?

### CODE REVIEW

**Comment by krisrok** [comment]
yes please! :) just stumbled upon that myself.

**Comment by krisrok** [comment]
@rid00z even if you don't merge, be so kind to update the documentation accordingly as it is really ambiguous saying "Now we can use both the ViewModel naming conventions."

**Comment by rid00z** [comment]
This would be a breaking change for other apps, it sounds great but can it be done in a non breaking change?

**Comment by blackice2999** [comment]
Hi, absolutely it may or not may breaking. It´s a bug and if someone use this method as is is he need to fix them. I am not a friend of encapsule so simple bugs in a workaround.

If you realy to avoid breaking a possible solution can be searching the assemblies if a class will be exists before replacing the name. Can Type.GetType() do this work ?

**Comment by rid00z** [comment]
Technically it's not a bug it's a preference. 

Many people already rely on this default, if you change it then it will break for many people. How do we accommodate those people?

**Comment by blackice2999** [comment]
You are the maintainer its your choice ;) I think its a simple bug and a commit message and release note should be enough for these peoples to change the code or stay on old version.

**Comment by blackice2999** [comment]
@rid00z 
What do you think about something like this? (Sorry if it is not perfect but iam new on C#)

`using System;

namespace FreshMvvm
{
    public class FreshPageModelMapper : IFreshPageModelMapper
    {
        public string GetPageTypeName (Type pageModelType)
        {
            var name = pageModelType.AssemblyQualifiedName;
            if (name.IndexOf ("PageModel") != -1)
                return name.Replace ("PageModel", "Page");

            if (name.IndexOf ("ViewModel") != -1) {
                if (Type.GetType (name.Replace ("ViewModel", "View")))
                    return name.Replace ("ViewModel", "View");

                if (Type.GetType (name.Replace ("ViewModel", "Page")))
                    return name.Replace ("ViewModel", "Page");
            }
        }
    }
`

**Comment by krisrok** [comment]
my take: https://github.com/rid00z/FreshMvvm/pull/71

**Comment by blackice2999** [comment]
I think it make sense to discuss this issue on a single place: #72

**Pull request closed without merging**
