### PR TITLE
Minor change in favour of inheriting MasterDetail navigation

### PR DESCRIPTION
**Pull request by jfversluis**
Fixed CustomImplementedNav (wasn't implementing new interface PopToRoot method) and exposed private properties in FreshMasterDetailNavigationContainer so that it's better inheritable.

I wanted the MasterDetail navigation as implemented but wasn't able to style it to my needs. By exposing the page collections I can use these to feed my custom Page for the menu.

### CODE REVIEW

**Comment by BNoohi** [comment]
@jfversluis Is this still a valid pull request? Looks like there are conflicts.

**Comment by rid00z** [comment]
I'm fairly sure this has already been done?

**Comment by jfversluis** [comment]
Correct! Can be closed!

**Comment by BNoohi** [comment]
@jfversluis I believe either you or @rid00z are the only ones with access to close this.

**Pull request closed without merging**
