### PR TITLE
Bugfix in PageModelMapper

### PR DESCRIPTION
**Pull request by escamoteur**
Although FreshMVVM should handle Mapping of xxViewModel => xxView it did map it to =>xxPage

### CODE REVIEW

**Comment by andrekiba** [comment]
Please merge!

**Comment by rid00z** [comment]
This would break people who prefer the way it's already implemented. I need to come up with a better solution that doesn't break others. I do understand that your preference and I will address this. 

@andrekiba You do know that it's very simple to override?

**Comment by andrekiba** [comment]
Hi @rid00z , yes sorry :-)

**Comment by robinmanuelthiel** [comment]
I actually like to have a `MainViewModel` for a `MainPage` which is supported by the current PageModelMapper but would break with this change. IMHO we should support all possible variations!

**Pull request closed without merging**
